document.write("Array")
document.write("<br>")
let a = [1,2,3,4,5]
document.write(a)
document.write("<br>")
document.write("<br>")
document.write("Inserting 200 at First position")
document.write("<br>")
document.write("<br>")
document.write(a.unshift(200))
document.write("<br>")
document.write("<br>")
document.write(a)
document.write("<br>")
document.write("<br>")
document.write("Inserting 35 at last position")
document.write("<br>")
document.write("<br>")
document.write(a.push(35))
document.write("<br>")
document.write("<br>")
document.write(a)
document.write("<br>")
document.write("<br>")
document.write("Deleting Middle Element")
document.write("<br>")
document.write("<br>")
document.write(a)
document.write("<br>")
document.write("<br>")
document.write(a.splice(3,1))
document.write("<br>")
document.write("<br>")
document.write(a)
document.write("<br>")
document.write("<br>")
document.write("Adding Javascript Text at 4 th element")
document.write("<br>")
document.write("<br>")
a[4]="Java Script"
document.write(a)